export const PREDEFINED_SKILLS = [
  // Frontend Technologies
  'React.js',
  'Vue.js',
  'Angular',
  'JavaScript',
  'TypeScript',
  'HTML',
  'CSS',
  'SASS/SCSS',
  'Tailwind CSS',
  'Bootstrap',
  'jQuery',
  'Next.js',
  'Nuxt.js',
  
  // Backend Technologies
  'Node.js',
  'Express.js',
  'Python',
  'Django',
  'Flask',
  'FastAPI',
  'Java',
  'Spring Boot',
  'C#',
  '.NET',
  'PHP',
  'Laravel',
  'Ruby',
  'Ruby on Rails',
  'Go',
  'Rust',
  
  // Databases
  'MongoDB',
  'MySQL',
  'PostgreSQL',
  'SQLite',
  'Redis',
  'Elasticsearch',
  'Firebase',
  'Supabase',
  
  // Cloud & DevOps
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'Docker',
  'Kubernetes',
  'Jenkins',
  'Git',
  'GitHub',
  'GitLab',
  'CI/CD',
  'Terraform',
  'Ansible',
  
  // Mobile Development
  'React Native',
  'Flutter',
  'Ionic',
  'Xamarin',
  'Swift',
  'Kotlin',
  'Android',
  'iOS',
  
  // Data Science & AI
  'Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Pandas',
  'NumPy',
  'Scikit-learn',
  'R',
  'MATLAB',
  'Data Analysis',
  'Data Visualization',
  
  // Testing
  'Jest',
  'Mocha',
  'Chai',
  'Cypress',
  'Selenium',
  'Unit Testing',
  'Integration Testing',
  'TDD',
  
  // Other Technologies
  'REST API',
  'GraphQL',
  'WebSocket',
  'Microservices',
  'Serverless',
  'Blockchain',
  'Web3',
  'Solidity',
  'Linux',
  'Windows',
  'macOS',
  'Agile',
  'Scrum',
  'JIRA',
  'Confluence',
  'Figma',
  'Adobe XD',
  'Photoshop',
  'Illustrator',
  
  // Programming Languages
  'C++',
  'C',
  'C#',
  'Java',
  'Python',
  'JavaScript',
  'TypeScript',
  'PHP',
  'Ruby',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'Scala',
  'R',
  'MATLAB',
  'Perl',
  'Haskell',
  'Clojure',
  'Erlang',
  'Elixir',
  
  // Frameworks & Libraries
  'React',
  'Vue',
  'Angular',
  'Svelte',
  'Ember.js',
  'Backbone.js',
  'Express',
  'Koa',
  'Hapi',
  'NestJS',
  'Fastify',
  'Spring',
  'Hibernate',
  'MyBatis',
  'Django',
  'Flask',
  'FastAPI',
  'Tornado',
  'Laravel',
  'Symfony',
  'CodeIgniter',
  'CakePHP',
  'Rails',
  'Sinatra',
  'Gin',
  'Echo',
  'Fiber',
  'Actix',
  'Rocket',
  'Axum',
  
  // Tools & Platforms
  'VS Code',
  'IntelliJ IDEA',
  'Eclipse',
  'Sublime Text',
  'Atom',
  'Vim',
  'Emacs',
  'Postman',
  'Insomnia',
  'Swagger',
  'Postman',
  'Thunder Client',
  'MongoDB Compass',
  'MySQL Workbench',
  'pgAdmin',
  'Redis Desktop Manager',
  'DBeaver',
  'TablePlus',
  'Sequel Pro',
  'phpMyAdmin',
  'Adminer',
  'Robo 3T',
  'Studio 3T',
  'MongoDB Atlas',
  'PlanetScale',
  'Supabase',
  'Firebase',
  'Vercel',
  'Netlify',
  'Heroku',
  'Railway',
  'DigitalOcean',
  'Linode',
  'Vultr',
  'Cloudflare',
  'AWS Lambda',
  'Azure Functions',
  'Google Cloud Functions',
  'Serverless Framework',
  'SAM',
  'CDK',
  'CloudFormation',
  'ARM Templates',
  'Pulumi',
  'Crossplane',
  'Helm',
  'Kustomize',
  'Skaffold',
  'Tilt',
  'Telepresence',
  'Istio',
  'Linkerd',
  'Consul',
  'Vault',
  'Nomad',
  'Prometheus',
  'Grafana',
  'ELK Stack',
  'Fluentd',
  'Jaeger',
  'Zipkin',
  'OpenTelemetry',
  'Sentry',
  'Bugsnag',
  'Rollbar',
  'LogRocket',
  'Mixpanel',
  'Amplitude',
  'Segment',
  'Google Analytics',
  'Hotjar',
  'FullStory',
  'Datadog',
  'New Relic',
  'AppDynamics',
  'Dynatrace',
  'Splunk',
  'Sumo Logic',
  'PagerDuty',
  'OpsGenie',
  'VictorOps',
  'StatusPage',
  'UptimeRobot',
  'Pingdom',
  'GTmetrix',
  'WebPageTest',
  'Lighthouse',
  'PageSpeed Insights',
  'Core Web Vitals',
  'Web Vitals',
  'Bundle Analyzer',
  'Webpack Bundle Analyzer',
  'Source Map Explorer',
  'Bundlephobia',
  'npm',
  'yarn',
  'pnpm',
  'Bower',
  'Composer',
  'Pip',
  'Conda',
  'Poetry',
  'Pipenv',
  'Virtualenv',
  'Pipx',
  'Homebrew',
  'Chocolatey',
  'Scoop',
  'Winget',
  'APT',
  'YUM',
  'DNF',
  'Pacman',
  'Portage',
  'Nix',
  'Guix',
  'Spack',
  'Conan',
  'vcpkg',
  'Hunter',
  'Buckaroo',
  'CPM',
  'FetchContent',
  'ExternalProject',
  'Hunter',
  'Buckaroo',
  'CPM',
  'FetchContent',
  'ExternalProject',
  'Hunter',
  'Buckaroo',
  'CPM',
  'FetchContent',
  'ExternalProject'
];

export const SKILL_CATEGORIES = {
  'Frontend': [
    'React.js', 'Vue.js', 'Angular', 'JavaScript', 'TypeScript', 'HTML', 'CSS', 
    'SASS/SCSS', 'Tailwind CSS', 'Bootstrap', 'jQuery', 'Next.js', 'Nuxt.js'
  ],
  'Backend': [
    'Node.js', 'Express.js', 'Python', 'Django', 'Flask', 'FastAPI', 'Java', 
    'Spring Boot', 'C#', '.NET', 'PHP', 'Laravel', 'Ruby', 'Ruby on Rails', 'Go', 'Rust'
  ],
  'Database': [
    'MongoDB', 'MySQL', 'PostgreSQL', 'SQLite', 'Redis', 'Elasticsearch', 'Firebase', 'Supabase'
  ],
  'Cloud & DevOps': [
    'AWS', 'Azure', 'Google Cloud Platform', 'Docker', 'Kubernetes', 'Jenkins', 
    'Git', 'GitHub', 'GitLab', 'CI/CD', 'Terraform', 'Ansible'
  ],
  'Mobile': [
    'React Native', 'Flutter', 'Ionic', 'Xamarin', 'Swift', 'Kotlin', 'Android', 'iOS'
  ],
  'Data Science': [
    'Machine Learning', 'Deep Learning', 'TensorFlow', 'PyTorch', 'Pandas', 
    'NumPy', 'Scikit-learn', 'R', 'MATLAB', 'Data Analysis', 'Data Visualization'
  ],
  'Testing': [
    'Jest', 'Mocha', 'Chai', 'Cypress', 'Selenium', 'Unit Testing', 'Integration Testing', 'TDD'
  ],
  'Other': [
    'REST API', 'GraphQL', 'WebSocket', 'Microservices', 'Serverless', 'Blockchain', 
    'Web3', 'Solidity', 'Linux', 'Windows', 'macOS', 'Agile', 'Scrum', 'JIRA', 'Confluence'
  ]
};
